[graph]
targets = []

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSL-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
exceptions = [
    { allow = ["GPL-3.0"], crate = "arborium-nginx" },
    { allow = ["MPL-2.0"], crate = "arborium-uiua" },
]

[advisories]
version = 2
ignore = []

[bans]
multiple-versions = "allow"
